chore: handle errors
updated the scripts to handle errors. This with the purpose of
hardening the scripts.

The error handling has logs printed to stederr.

diff --git a/scripts/run_services b/scripts/run_services
--- a/scripts/run_services
+++ b/scripts/run_services
@@ -14,7 +14,7 @@ while [[ $# -gt 0 ]]; do
       shift
       ;;
     --help)
-      echo "Usage: $0 [--log] <execution_order_file> <path/to/binaries> <path/to/logs>"
+      echo "Usage: $0 <execution_order_file> <path/to/binaries> <path/to/logs> [--log]"
       echo "  --log  When specified, services will write stdout and stderr to a log file in the log path"
       exit 0
       ;;
@@ -24,34 +24,55 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
+logs_path=logs
+check_for_logging(){
+  if [ $logging = true ]; then
+    if ! [ -d "$logs_path" ]; then
+      mkdir "$logs_path"
+    fi
+  fi
+}
+
 # Define paths
 execution_order_file=$(realpath "$1")
-binaries_path=$(realpath "$2")
-if [ $logging = true ]; then
-  logs_path=$(realpath "$3")
+if ! [ -f "$execution_order_file" ]; then
+  printf "Invalid execution path\n %s" "$execution_order_file" >&2
+  exit 1 
 fi
 
-mapfile -t main_array < "$execution_order_file"
-cd "$logs_path" || exit 1
-for file in "${main_array[@]}"; do
+binaries_path=$(realpath "$2")
+check_for_logging
+
+handle_logging(){
+  file=$1
   if [ $logging = true ]; then
     log_file_name="$file.log"
-    
     if ! [ -f "$log_file_name" ]; then
       touch "$log_file_name"
     fi
-
     { printf '%.s-' {1..50}; echo; date; echo "This is a new run"; printf '%.s-' {1..50}; echo -e "\n"; } >> "$log_file_name"
   fi
+}
+
+mapfile -t main_array < "$execution_order_file"
+for file in "${main_array[@]}"; do
+  handle_logging "$file"
 
   folder=$(find "$binaries_path" -type d -name "$file*boot*")
+  if [ -z "$folder" ]; then
+    echo "Could not find binary: $file" >&2
+    exit 1 
+  fi
 
+  binary="$folder/bin/$file"
   if [ $logging = true ]; then
-    "$folder/bin/$file" >> "$log_file_name" 2>&1  &
+    "$binary" >> "$logs_path/$log_file_name" 2>&1  &
   else
-    "$folder/bin/$file" > /dev/null 2>&1   &
+    "$binary" > /dev/null 2>&1 &
   fi
 
   bg_pid=$!
   echo "$file has started with process PID: $bg_pid"
 done
+
+exit 0
