chore: update money exchange CI/CD workflow
I have updated the workflow to run test scripts and pack the binaries
and logs. In this way we can know if the service is running as expected
and can recieve and send requests.

The test scripts that will be executed by the CI/CD pipeline for
the services will be located in the "services_testing" folder.

Created two scripts to test the money_exchange microservice.
- service_startup: it creates the enviroment to run the service tests
- simple_test: this script runs a simple query to check if the gateway
  is connected.

diff --git a/.github/workflows/money_exchange_workflow.yml b/.github/workflows/money_exchange_workflow.yml
--- a/.github/workflows/money_exchange_workflow.yml
+++ b/.github/workflows/money_exchange_workflow.yml
@@ -82,3 +82,40 @@ jobs:
           cd backend/money_exchange
           ./gradlew --no-daemon checkStyleMain spotlessCheck -x checkStyleTest -x test build 
 
+  service_integration:
+    name: service_integration
+    runs-on: ubuntu-latest
+    needs: check
+
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
+
+    - name: Setup JDK
+      uses: actions/setup-java@v3
+      with:
+         distribution: 'temurin'
+         java-version: '17'
+         cache: 'gradle'
+
+    - name: Money Exchange Integration testing
+      id: integration_testing
+      working-directory: ${{ github.workspace }}
+      run: |
+          exit_code=0
+          ./services_testing/money_exchange/service_startup
+          if ! ./services_testing/money_exchange/simple_test; then
+            echo "Test failed"
+            exit_code=1
+          fi
+
+          ./scripts/utils -k
+          exit $exit_code
+
+    - name: Upload a Build Artifact
+      uses: actions/upload-artifact@v3.1.3
+      with:
+        name: fake_orgasm_app-${{ github.sha }}
+        path: logs
+      if: always()
+            
